### ISSUE TITLE
Question : Can I participate if my PhD director has a contract with Renault?

### ISSUE THREAD

**Issue by AllergicMushroom** [renault-iaa/challenge-roadef-2022#1]
I'm a student in my master degree's last year and would like to participate. Starting September, I'll be in a PhD program but my PhD director has a contract with Renault. Can I still register and participate?

**Comment by renault-iaa** [comment]
Hello, can you tell who your PhD director is and what is the scope of his contract with Renault ? Is it about optimization for the supply chain ?

**Comment by renault-iaa** [comment]
Hello @Rynhho, we have talked with your PhD director. The contract is not about the scope of the challenge and he does not intend to participate to the challenge with you, so no problem to your participation.
