### ISSUE TITLE
Questions about input_items.csv

### ISSUE THREAD

**Issue by thetopjiji** [renault-iaa/challenge-roadef-2022#11]
Hi, 

I have some questions about the input_items.csv

- In column C (supplier dock), only several items have code, is this phenomenon normal?
- From column N to column S, it seems that the data does not corropond to the heading of the column. For example, in column P (Earliest arrival time), some data like 'widthwise' is quite strange here.
- The last column (T), there is no heading.

Speculations:
- In French, the researchers always use ',' as the decimal point. We think there may be a problem between columns L and M. When you try to write 144,600, LibreOffice reads it as two separate data '144' and '600'. 
- Some differences between the English version (we use) and the French version (you use) in LibreOffice.

**Comment by houcem-chaabane-aqsone** [comment]
I faced the same issue with csv parsing in excel (english version). The solution I found is to open an empty excel file then click on "data" then "from text" , open "input_items.csv" and then choose "delimited" then choose "tab" and "semicolon"

**Comment by renault-iaa** [comment]
The answers to your questions :

**In column C (supplier dock), only several items have code, is this phenomenon normal?** 
Yes the column “supplier dock” may be empty.

**- In French, the researchers always use ',' as the decimal point. We think there may be a problem between columns L and M. When you try to write 144,600, LibreOffice reads it as two separate data '144' and '600'. 
- Some differences between the English version (we use) and the French version (you use) in LibreOffice**
In the version 1.1 of the rules, we precise that the decimal separator is “,” and not “.”. We just publish a new version v1.2 of the rules which defines “;” as the separator for csv files. You have to set the 2 separators in your libre office.

**Comment by renault-iaa** [comment]
Yes the column “supplier dock” may be empty for some items.

In the version 1.1 of the rules, we precise that the decimal separator is “,” and not “.”. We just publish a new version v1.2 of the rules which defines “;” as the separator for csv files. You have to set the 2 separators in your libre office.

**Comment by thetopjiji** [comment]
> I faced the same issue with csv parsing in excel (english version). The solution I found is to open an empty excel file then click on "data" then "from text" , open "input_items.csv" and then choose "delimited" then choose "tab" and "semicolon"

Thanks for your advice! I will try it too.

**Comment by thetopjiji** [comment]
> Yes the column “supplier dock” may be empty for some items.
> 
> In the version 1.1 of the rules, we precise that the decimal separator is “,” and not “.”. We just publish a new version v1.2 of the rules which defines “;” as the separator for csv files. You have to set the 2 separators in your libre office.

Thanks for your help. I'll try it.
