### ISSUE TITLE
Question about allocation granularity 

### ISSUE THREAD

**Issue by houcem-chaabane-aqsone** [renault-iaa/challenge-roadef-2022#12]
Hello,

The item table provides information about the **global items** :  For instance global item 0091017300_03072022000007 from VA2 has 15 **unitary items**.  Let's note them : [0091017300_03072022000007_unit_1, 0091017300_03072022000007_unit_2, 0091017300_03072022000007_unit_3, ..., 0091017300_03072022000007_unit_15]

Does the allocation problem try to solve : 
1) The allocation of the **global item** to one truck ?  (meaning that all the 15 units must be loaded in one truck)
or
2) The allocation of each of the **unitary items** to one truck ? (meaning that each of the 15 units can be loaded separately ) 

Thank you 
Houcem

**Comment by renault-iaa** [comment]
Hello,

The correct answer is the second proposal. You have to load 15 unitary items (all with the same characteristics described in the item_id) and the 15 items can be loaded into different trucks.

Best regards
Alain Nguyen

**Comment by houcem-chaabane-aqsone** [comment]
Thanks for your answer
