### ISSUE TITLE
How to handle data issues

### ISSUE THREAD

**Issue by DavidGarHeredia** [renault-iaa/challenge-roadef-2022#13]
Hi there!

I was looking at the latest version of the data (commit 5882d6ee35869df373dbf7563d60dd76dc42ccad) and I think there may be an error. 

In `datasetA/TR/input_trucks.csv` the truck with `id = P202420411` has 2 different values for `Max weight on the bottom item in stacks` (100000 and 750). As far as I understand, this contradicts what is said in the PDF with the rules.

Regardless of the existing error (or not), I was wondering if there was any expectation about how to handle these situations. For example, "pick the most favorable value", or "throw an exception", or "print a warning on the screen"... In the end, these kinds of data errors are difficult to avoid in any dataset, so it is better to have a standard to deal with them :)

Thanks in advance!

David

**Comment by renault-iaa** [comment]
Hello,

The rules (and subject) are misleading, I will correct the documents. The maximal weight above the bottom item are associated with the truck and the product. That is why there can be several max weight for the same truck id. It is because some products (which can be loaded into the truck) are packaged in cardboards, which cannot bear more than 750 kg above them, while other products (which can be loaded into the same truck) are packaged in metallic boxes which can bear much heavier weights above them.

Best regards
Alain Nguyen

**Comment by DavidGarHeredia** [comment]
Hi!

Thanks for the answer! Now it makes sense :)

On the other hand, regarding the part about how to handle potential inconsistencies in the data (e.g., https://github.com/renault-iaa/challenge-roadef-2022/issues/9), any suggestions? In the dev phase, we can simply open an issue, but when the algorithm is being executed it has to make a decision about it.

Thanks again!

David

**Comment by renault-iaa** [comment]
I suggest your code just throw an exception in case of inconsistencies in data.

**Comment by DavidGarHeredia** [comment]
Cool. Thanks a lot!

**Comment by fontanf** [comment]
@renault-iaa In this case, does the constraint only applies to the bottom item? If the bottom item of a stack is in a metallic box and the item right above is in a cardboard, then shouldn't the constraint be checked for both items? Or maybe an item in a cardboard cannot have the same stackability code as an item in a metallic box?

**Comment by renault-iaa** [comment]
@fontanf The second assumption is correct :  an item in a cardboard cannot have the same stackability code as an item in a metallic box. We cannot mix metallic boxes /cardboards / pallets in the same stack.

**Comment by fontanf** [comment]
Thanks!
