### ISSUE TITLE
Planned Trucks Cost Question

### ISSUE THREAD

**Issue by aphi** [renault-iaa/challenge-roadef-2022#14]
Hi - does every planned truck have to be paid for, regardless of whether it's used for any items? This would make the total cost of planned trucks to be fixed. Or alternatively, is it possible to only use a subset of planned trucks, and only pay for the planned trucks used?

**Comment by renault-iaa** [comment]
Hello,

No, only planned trucks actually used are paid for. So the planned trucks without any item are not paid. And we have also to pay the extra trucks if they are needed.

Best regards
Alain Nguyen

**Comment by aphi** [comment]
Thank you!
