### ISSUE TITLE
Constraint (S6)

### ISSUE THREAD

**Issue by fontanf** [renault-iaa/challenge-roadef-2022#16]
Constraint (S6) is not clear to me:

> The number of items i packed in a stack s must not exceed the smallest "max stackability" ISMi of the
items i.
 
Does that mean that:
* For each item i, the number of items i in a stack must not exceed ISMi
* For each item i in a given stack, the number of items in this stack must not exceed ISMi
?

**Comment by renault-iaa** [comment]
Hello,

Yes, the 2 assumptions are correct. The second assumption implies the first one.

The meaning of constraint S6 is : 
for any stack s, the number of items in stack s cannot exceed the smallest "max stackability" ISM associated with the items of stack s.

**Comment by fontanf** [comment]
Thanks, that's clear now
