### ISSUE TITLE
Checker - extra truck cost

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#17]
Hi,
I would like to ask if the checker gives the correct objective for extra trucks. If I understand correctly an extra truck should cost: truck_cost * (1 + alpha_e). But I think the checker calculates with truck_cost * alpha_e. Can you please check it? 

Also, inventory cost doesn't look right to me. It gives 0 most of the time, even though many items arrive days before their latest arrivals.

**Comment by renault-iaa** [comment]
Hello,

You are right about the cost of extra trucks : there is a mistake in the calculation by the checker. I will publish soon a new version.
About the inventory cost, can you give us an example (item id, truck id) where the inventory cost is zero and there are days between the arrival day and the latest arrival time ?

Best regards
Alain Nguyen

**Comment by tomash1234** [comment]
Sure. Checker gives the inventory cost 0 for my solution of AS dataset, but for example
item: 0090018000_03072022000341, arrivals: 2022 08 26 0000 - 2022 08 29 0915
truck: P238731303, arriving 2022 08 26 1430. If I understand it correctly that should be 3 days. (3*inventory_cost=15)

another item:
item: 0090018000_03072022000006, arrivals: 2022 08 23 0000 - 2022 08 24 1020
truck_id: P235709601, arrival: 2022 08 23 1020, 1 day earlier

**Comment by renault-iaa** [comment]
You are right : there was a problem in the totaling of the inventory cost by the checker. I will commit a new version of the checker today. Thanks for the notice.

**Comment by tomash1234** [comment]
Nice! Now the checker and my implementation give the same values. Thanks!
