### ISSUE TITLE
[datasetA: MT, RT] - Plant dock Loading order = 0 for multiple docks

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#18]
Hi,
I am not sure how I should handle if the plant dock loading order equals 0 for multiple plant docks. This occurs in dataset MT, truckId= P208512301. There are docks 177GRF, 177GRI, 177GRE and all of them have loading order 0. And in the dataset RT, there are all plant docks loading order = 0. Is it an error in the dataset or is it intentional?

**Comment by renault-iaa** [comment]
Hello,

When the plant dock loading order is identical between several plant docks, it means that there is no constraint on the loading order between these plant docks. The constraint P4 applies only when docks loading orders are different. I will give these precisions in the next version of the subject.

Best regards
Alain

**Comment by tomash1234** [comment]
Ok, thank you very much for the clarification.
