### ISSUE TITLE
Input interpretation doubts

### ISSUE THREAD

**Issue by DavidGarHeredia** [renault-iaa/challenge-roadef-2022#2]
Hi there!

I was looking at the input data provided in the repo and came across a few questions. Let me list them by file.

**Items file**

1. The "supplier dock" column may be empty. Does this mean that there is only one dock for the associated supplier code, or how should I interpret this?

2. For a given "Item ident", let's say that column "Number of items" shows a value equal to 3. What is the meaning of this?
     1. At the end of the planning period, we will need to have packed the 3 items of that Item ident, but we can do it in different trucks and time periods.
     2. When packing the Item ident, we need to pack the 3 items in the same truck and stack. So if the stack were composed only of those 3 items, the height will be `3 times the value shown in column "Height" - 2 times the value shown in "Nesting height"`.
     3. As the previous point but the items do not have to be in the same stack.

**Trucks file**

1. Same question as for Items file: What is the interpretation when the "supplier dock" column is empty?

2. The input-description PDF says: "Planned trucks are defined for every n-uplet supplier/plant/product/arrival time". Does this mean that if in a file there are M unique combinations of these n-uplets we have M planned trucks available? Or does the number of trucks equal the number of unique values in column "Id truck"?

Thanks in advance!

**Comment by renault-iaa** [comment]
Dear @DavidGarHeredia ,

**Items file** 

(1) some suppliers may have several supplier docks and some suppliers may have no supplier dock. When the "supplier dock" column is empty, it means that the supplier has no supplier dock.
(2) yes, at the end of the planning period, you must have packed the 3 items of that Item ident, in one or several stacks, and in one or several trucks.

**Trucks file**
(1) It means that the supplier has no supplier dock.
(2) For every tuple supplier/plant/product/arrival time, there is only one planned truck. And the number of planned trucks is equal to the number of unique values in column "id truck".

Best regards
Alain Nguyen
