### ISSUE TITLE
Checker S7: Stack density conditional calculates in wrong units 

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#24]
Hi,
I noticed that the checker never reported that a stack exceeds maximal density (S7). So I checked the checker code and it looks like the unit of `stackDensity` is kg/mm^2 weather getMaxStackDensity() returns the value in kg/m^2 (according to the table Rule pdf file).

`double stackDensity = stackWeight / ((stack.getxExtremity() - stack.getxOrigin()) * (stack.getyExtremity() - stack.getyOrigin()));`

`if (stackDensity > stack.getOutputTruck().getInputTruck().getMaxStackDensity())`
`

**Comment by renault-iaa** [comment]
Hello,

You are absolutely right : the problem is now solved in the last version committed v1.6.0. Thanks for the notice.

**Comment by tomash1234** [comment]
Nice! Thank you!
