### ISSUE TITLE
Checker does not check loaded volume

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#25]
Hi,
I think that the checker never checks if the loaded volume provided in the output trucks file is correct. I don't know if it is needed for the challenge, but maybe it should be checked.

**Comment by renault-iaa** [comment]
Hello,

You are right : the checker should check the volume, as well as the loaded length. Among the indicators, it checks only the loaded weight. Extra checks will be done in the next release of the checker.

**Comment by renault-iaa** [comment]
Hello,

The check of loaded volume is now performed in the last version committed v1.6.0.
