### ISSUE TITLE
Clarifications: Single Plant, and Runtime limit

### ISSUE THREAD

**Issue by aphi** [renault-iaa/challenge-roadef-2022#26]
Hi, can I ask 2 things:

1: Is it true that there's only ever one plant per problem instance? There can be multiple plant docks, but there's only one plant. If there were multiple plants, there would need to a defined plant loading order.

I assumed this was the case but just wanted to check since some of the terminology is flexible to accommodate multiple plants e.g.
```
IP_i : destination plant of item i

Parameters IPi ... will determine which trucks can be used to load the item i
```

2: Are there any approximate bounds you can give on the 'Runtime limit' parameter? This is important since a quite different algorithmic approach may be required if the Runtime has the potential to be very short.

Thank you

**Comment by renault-iaa** [comment]
Hello,

Yes there is only one plant per problem instance.

In terms of timelimit, it may range from 30 min for small instances up to 60 min for huge instances.
