### ISSUE TITLE
Checker Output Truck loaded volume

### ISSUE THREAD

**Issue by gfpantoja** [renault-iaa/challenge-roadef-2022#28]
Hello dear organizers, 

I have an issue when checking my solution for the instance VA2. According to the report file, I only have this type of error. 
I chose one specific case so I could express myself better.
Let's consider the truck P249501101, which has a length of 13500 mm, a width of 2440 mm, and a height of 3000 mm. This means that the total available volume is 98,82 m3.

The message that I got from the report for this truck is shown as follows:
Output truck;the loaded volume is incorrect;truck id = P249501101;loaded volume read in output truck file = 94,72;total stacks volume = 99,79

And the output files that I used have the following:

Trucks output
![image](https://user-images.githubusercontent.com/68205100/190480075-7f0be95f-fb7c-4db2-b63d-df26091fed97.png)

Stacks output
![image](https://user-images.githubusercontent.com/68205100/190480164-cffbf9f2-39f4-4d71-84d4-73cb3e05c549.png)

If you check these images, you will find that the loaded stacks' volume is 94,72. I do not know where the 99,79 comes from, mainly because the 99,79 is greater than the total volume of the truck (98,82). Therefore, I do not understand what exactly I should correct.

I would appreciate it if you could guide me about what I should print in the output files or if this is a checker's bug.

**Comment by tomash1234** [comment]
Hi, I have the same problem. I got it in a different instance (CA). I checked the code of Checker and I think it isn't calculating with the item's nesting height, that's why the volume is greater than the real one. I guess this is a bug.

**Comment by renault-iaa** [comment]
Hello,

You are completely right : it is a bug of the checker ! I will correct it for the next release. Thanks for your vigilance.

**Comment by renault-iaa** [comment]
The new version v1.7.0 of the checker corrects the bug on the check of loaded volume.

**Comment by gfpantoja** [comment]
Hello, I tryed the last version of the checker (v.1.7.0) but now the total stacks volume is underestimated. For example, in the instance AS I got the following in the report file:

![image](https://user-images.githubusercontent.com/68205100/191321255-53d6edb9-55c4-43af-9770-31da0747c3c1.png)

The output_stacks has the following:

![image](https://user-images.githubusercontent.com/68205100/191321364-622e741f-cf65-4846-838d-3534de19ac1d.png)

The output_trucks has the following:

![image](https://user-images.githubusercontent.com/68205100/191321488-f0c205c7-49f2-451a-86e7-fdc8a71da495.png)

The volume of loaded stacks is 61.34, however, the report file says that it is 18.39

**Comment by renault-iaa** [comment]
Hello,

Can you send me your solution files for AS ? (output items, output stacks, output trucks)

alain.nguyen@renault.com

**Comment by renault-iaa** [comment]
Hello,

The problem is solved with the latest version v1.7.1 of the checker.

**Comment by gfpantoja** [comment]
Hello, I tried the latest version of the checker and it now works fine. Thank you!
