### ISSUE TITLE
Missing product codes

### ISSUE THREAD

**Issue by fontanf** [renault-iaa/challenge-roadef-2022#29]
Hi,

Is it normal that some product codes mentioned in the `input_trucks.csv` file are not referenced in the `input_items.csv` file?

For example, in instance `AS`, the product code `751717215R` lines 71, 151, 340...

Should we ignore these lines?

**Comment by gfpantoja** [comment]
Hi, I have been ignoring them, and I get feasible solutions according to the checker. I think the important thing is to pack all items in the items file.

**Comment by fontanf** [comment]
Thanks for your answer. I'm asking so we can be sure that's its not an error in the instance, like missing items

**Comment by renault-iaa** [comment]
Hello,

Yes the product codes mentioned in the input trucks file may not be present in the items file. For instance, a product may not be used anymore by Renault plants, but the transportation documentation (the input trucks file) has not been updated.

**Comment by fontanf** [comment]
Thanks, that's clear
