### ISSUE TITLE
Improvement of Checker 1.7.1

### ISSUE THREAD

**Issue by sami-ka** [renault-iaa/challenge-roadef-2022#31]
Hi,

I feel checker v1.7.1 should be modified when writing the report as the header and rows have different numbers of fields in each.

Here are the header and one other lines I get from the report : 

## Header
scope;anomaly;data

|scope|anomaly|data|
|------|----|----|

## First row
Output truck;the loaded volume is incorrect;truck id = Q192402701_100;loaded volume read in output truck file = 829498860,00;total stacks volume = 0,83

|Output truck|the loaded volume is incorrect|truck id = Q192402701_100|loaded volume read in output truck file = 829498860,00|total stacks volume = 0,83
|------|----|----|---|---|

## Further line in the report

Output truck;the weight on middle axle of the trailer is incorrect;truck id = Q192402701_100;weight on middle axle of the trailer read in output truck file = 5062,36;recalculated  weight on middle axle of the trailer = 4694,93;total stacks weight = 588,40;distance between center of gravity of stacks and end of the trailer = 603,00;distance between center of gravity of stacks and rear axle of the trailer = 8697,00;weight on the harness of the trailer = 2919,05

Output truck|the weight on middle axle of the trailer is incorrect|truck id = Q192402701_100|weight on middle axle of the trailer read in output truck file = 5062,36|recalculated  weight on middle axle of the trailer = 4694,93|total stacks weight = 588,40|distance between center of gravity of stacks and end of the trailer = 603,00|distance between center of gravity of stacks and rear axle of the trailer = 8697,00|weight on the harness of the trailer = 2919,05
|------|----|----|---|---|---|---|---|---|

Would it be possible to write the data column with  another character than ";" ? 
I guess "." or "|" could be a good choice.

From what I've read from the checker code, this would probably only impact the file :

> model/checker.java

Thanks for your support!

**Comment by renault-iaa** [comment]
Hello,

We use the separator ";" because it is the "natural" separator for excel or calc (libre office) to display columns. We use the same separator for all the input and output files. And we prefer to keep it that way.

**Comment by sami-ka** [comment]
@renault-iaa 

Maybe to clarify, I do not want to change the **;** separator. 
In your header you have 3 columns separated by **;** : scope, anomaly and data.

In the report, the checker writes comment with the **;** character like the example hereafter : 

> Output truck **;** the loaded volume is incorrect **;** truck id = Q192402701_100 **;** loaded volume read in output truck file = 829498860,00 **;** total stacks volume = 0,83

This corresponds to 5 columns when you look at the **;** character as separator. This does not correspond to the number of columns in the header. To add to this, there are also lines with an equivalent of 9 columns in the same report. 

I was proposing to just change the comment supposed to be in the data column with another character (for instance **.**), in order to have something like this afterward : 
> Output truck **;** the loaded volume is incorrect **;** truck id = Q192402701_100. loaded volume read in output truck file = 829498860,00. total stacks volume = 0,83

With this change, there should be a consistent number of columns throughout the rows of the report.
We already made an adjustment to be able to read the report outside of excel and calc properly, but I felt this could make things easier for other teams in the future.

I will close the issue and let you do as you feel is more suited for everyone.

**Comment by renault-iaa** [comment]
OK I understand your viewpoint. The headers of the report file may be misleading. In fact, the number of columns of data cannot be the same for all types of anomalies. The use of column separator among the data columns allows you to filter according to data, for instance to filter on an anomaly message in order to get all the records associated with the same type of  anomaly.
