### ISSUE TITLE
Checker - Forced orientation

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#32]
Hi,
I am not sure about the items' forced orientation. I understand constrain S4, that there cannot be two different forced orientations in one stack. But I suspect that there is no check a stack is actually orientated as it is forced. 

I believed I had a stack with widthwise forced orientation items, but the whole stack was placed lengthwise, and the checker didn't report anything.
How does it work exactly? Is there a constraint similar to this?

 $\forall s (\space so_s = lengthwise \implies sx^o_s + sl_s = sx^e_s)  \land (so_s = widthwise \implies sx^o_s + sw_s = sx^e_s)$

**Comment by renault-iaa** [comment]
Hello,

You are right : the check of constraint S4 is uncomplete in the checker. We just check that all the items of a stack have either the same forced orientation, or no forced orientation. And the constraint to be satisfied is the one you display (cf paragraph 2.3 in the subject). We will deliver soon a new version of the checker to add the checks on forced orientation. Thanks for your vigilance.

**Comment by renault-iaa** [comment]
hello,

the new version v1.8.0 of the checker makes a complete check of constraint S4 on forced orientration.

**Comment by tomash1234** [comment]
thanks!
