### ISSUE TITLE
Sprint phase submission

### ISSUE THREAD

**Issue by aphi** [renault-iaa/challenge-roadef-2022#33]
For the sprint phase, do we just submit a computational results table and solutions files? Is it the intention that the solutions are generated under the same CPU and time limit conditions as will be used in the final phase? (If so I'm just pointing out that it's not really possible to ensure everyone is following those conditions.)

What exact time and timezone is the deadline for submission? (It just says October, 15th 2022)

Thanks

**Comment by renault-iaa** [comment]
hello, 

for the sprint phase, you just need to submit solutions files and computational results : https://www.roadef.org/challenge/2022/en/index.php

the deadline for submission is October, 15th 2022 at 23:59 Paris time.

**Comment by aphi** [comment]
Ok thanks.

And is it the intention that the sprint phase solutions are generated with respect to the stated problem time limit? I'm just noting it will be difficult/impossible to ensure people were indeed doing that.

**Comment by renault-iaa** [comment]
No there is no timelimit for the sprint phase.
