### ISSUE TITLE
Error in the checker!

### ISSUE THREAD

**Issue by JaiWason** [renault-iaa/challenge-roadef-2022#35]
I am getting the following error while using the checker to check my output files. Please help me resolve this issue.
![Error](https://user-images.githubusercontent.com/88794154/194928477-f42eb246-d87c-4d3d-ae90-24217d52f3c3.jpeg)

**Comment by renault-iaa** [comment]
Hello, 

The crash was due to empty stacks and missing items in the results. The new version v1.9.0 of the checker manages properly these issues.
