### ISSUE TITLE
Nesting height in solution files

### ISSUE THREAD

**Issue by ru-sec** [renault-iaa/challenge-roadef-2022#36]
When writing the solution files, should we subtract the nesting height from the item on top or on the bottom?
E.g. if item 1 has height=50, nesting_height=5 and item 2 (which is above item 1) has height=50, what should be the coordinates in the output file for these items?
Option 1:
item 1: Z origin = 0
item 1: Z extremity = 50
item 2: Z origin = 50
item 2: Z extremity = 100 (50+50)

Option 2:
item 1: Z origin = 0
item 1: Z extremity = 45 (50-5)
item 2: Z origin = 45
item 2: Z extremity = 95 (45+50)

Option 3:
item 1: Z origin = 0
item 1: Z extremity = 50
item 2: Z origin = 45
item 2: Z extremity = 95 (45+50)

Thanks in advance for the support

**Comment by renault-iaa** [comment]
Hello,

We give the following rule in the subject (2.1) : "An item $i$ has a nesting height $\widehat {IH}_i$, which is used for the calculation of the height of stacks : if item $i_1$ is packed above item $i_2$, then the total height is $IH_{i_1} + IH_{i_2} - \widehat {IH}_{i_1}$". So you should substract the nesting heights of all the items in the stack, except the bottom item.

**Comment by ru-sec** [comment]
Thanks for the answer. The nesting height for stack is clear to me. My question is how we should report the Z coordinates of items in the `output_items.csv`. Should we consider the nesting height in there? and in such a case which option from above is correct (if any?)

**Comment by renault-iaa** [comment]
hello,

the right option for the checker is the following : 
item 1: Z origin = 0
item 1: Z extremity = 50
item 2: Z origin = 50
item 2: Z extremity = 95
it is arbitrary.

**Comment by ru-sec** [comment]
Thanks for the feedback. However, I still don't get why the item2 Z origin is 50 and not 45 since it is partially stacked inside Item 1. What I would have expected is

item 1: Z origin = 0
item 1: Z extremity = 50
item 2: Z origin = 45
item 2: Z extremity = 95 (45+50)

**Comment by renault-iaa** [comment]
As I said, it is an arbitrary choice.
