### ISSUE TITLE
[Dataset B - BY, BY2] Truck (P312066801) EMmm too small

### ISSUE THREAD

**Issue by tomash1234** [renault-iaa/challenge-roadef-2022#37]
Hi,
I am checking new instances BY and BY2  (dataset B). And there is a truck "P312066801", whose EMmm is only 2000, that's too small to suit even an empty truck. I wonder if it is intentional or an error in the instances.

**Comment by renault-iaa** [comment]
Hello,

You are right : the EMmm should not be 2000, it is a bug. Thanks for your vigilance, I will check all the instances and publish a new version of the dataset B.
