### ISSUE TITLE
truckId not starting with P

### ISSUE THREAD

**Issue by hsimonis** [renault-iaa/challenge-roadef-2022#38]
Dear organizers,
the trucks.csv file of instance VA in dataset B contains a truckId
"F315566505" not starting with a "P". When creating a copy of this
planned truck, what should the id of the copied truck be? Should it
start with "G", with "Q", or should entries not starting with "P" be
ignored?

Best regards

Helmut

**Comment by renault-iaa** [comment]
Hello,

When creating a copy of the planned trucks "F....", the truck ident should also start with "Q". Thanks for your vigilance.

**Comment by renault-iaa** [comment]
Hello,

In fact, you should not find Fxxxxxxx planned trucks. We will update datasetB asap. sorry for the incovenience.

**Comment by renault-iaa** [comment]
We just publish a new version of dataset B where Fxxxxxxx planned trucks have been renamed into Pxxxxxx planned trucks.
