### ISSUE TITLE
short and very long trailers n DatasetB instance AS

### ISSUE THREAD

**Issue by hsimonis** [renault-iaa/challenge-roadef-2022#39]
Dear organizers,
I have a question
about the trailer types used. In instance AS for example, there are
quite short (8.6m) and very long trailers (24.84m). These types still
have the same empty weight and distance between Harness (fifth wheel, kingpin) and rear axle,
creating a massive overhang on the long trailers. My questions:

a) Is this intentional?

b) It is easy to lift the middle axle (negative weight on middle axle)
when filling the overhang at the end of the long trailer. There is no
stated constraint that the axle weights have to be positive, would a
negative mid axle weight be OK in a solution?

c) These short and long trailer types seem quite unrealistic with the
data given, shouldn't the other parameters be changed as well when
creating shorter or longer trailers in the instances?

d) if these vehicle really are trucks (with pulled trailers) should they be modelled as such instead of semi-trailers?

Helmut

**Comment by renault-iaa** [comment]
Hello,

Thanks for your questions. These very special trucks are used in our Brazilians plants. You are right, the existing parameters for axle weights are not appropriate for these trucks. We will adjust the axle parameters for these trucks by mid november.

**Comment by renault-iaa** [comment]
Hello,

We modify the truck dimensions of very short and very trailers of instances AS and AS2, to make them compatible with axles parameters. The new dataset B has been published.
