### ISSUE TITLE
Unusable planned trucks?

### ISSUE THREAD

**Issue by 4colors-research** [renault-iaa/challenge-roadef-2022#40]
Hi, 

Thank you for launching this nice competition! 

It seems that in many instances there are trucks (truck ids) in the trucks file that are not referenced by any of the product codes present in the items file. For example, in the instance VA (dataset B), truck P349554503 can only carry products with one code: 760129565R. This code, however, does not appear in the items file of this instance. It seems like that are planned trucks that can never be used. This also seems to be the case with most instances in both datasets. 

I just want to double check if that is correct, and if so, is it intentional? Thank you.

**Comment by renault-iaa** [comment]
Hello,

Yes you can find trucks which are not useful. We generate the trucks file from a database, which may contain historical trucks no longer used.

**Comment by 4colors-research** [comment]
I see. Thank you!

**Comment by 4colors-research** [comment]
Another related point to clarify. Section 2.4 says "The transportation cost is the total cost of planned and extra trucks". Do all planned trucks go into the objective function or only selected ones that are going to be dispatched? In other words, does \tilde{T} must contain all planned trucks? Thank you.

**Comment by renault-iaa** [comment]
The transportation cost is related only to the trucks really used, that is the trucks where items are loaded into.

**Comment by 4colors-research** [comment]
Thank you!
