### ISSUE TITLE
"stack with multiple docks" constraint

### ISSUE THREAD

**Issue by ru-sec** [renault-iaa/challenge-roadef-2022#42]
Hello,
I have a question about the stack with multiple docks constraint.
If `TF_t=True`, then a stack may contain items with 2 plant docks with **consecutive** loading orders. What does consecutive mean in this case? For instance, if in one truck I have items for plant dock A with loading order 1 and plant dock C with loading order 3 (and I am missing plan dock B with loading order 2), then can plant dock A and C be considered as consecutive?

**Comment by renault-iaa** [comment]
Hello,

You are right : if plant dock B with loading order 2 is missing in the truck, then plant docks A and C (with respective loading orders of 1 and 3) can be considered as consecutive. We have to upgrade the checker, which does not yet take into account the potential missing of intermediate plant docks.

**Comment by renault-iaa** [comment]
Hello,

The new version v1.10.0 of the checker manages properly the use cases where some plant docks are missing in a truck, when checking constraint S3.
