### ISSUE TITLE
Extra trucks

### ISSUE THREAD

**Issue by MaiteAlonso** [renault-iaa/challenge-roadef-2022#44]
Hello,

The instances VA and VA2, have trucks with Id starts by 'F'.
What is the code for an extra truck? 'Q' or 'G'

Sometimes, in these instances, the checker says :"output items file; truck id unknown in the outputs trucks; truck id = QXXXXXXXXX_1'
when it is added an extra truck for an F planned truck.

Thank you

**Comment by renault-iaa** [comment]
Hello,

You should not encounter the Fxxxxxxx planned trucks, there is an issue with dataset B. We will update dataset B asap. You are right, the error message you cited is due to the fact that the checker does not manage Fxxxxxxx planned trucks.

Thanks for your vigilance.

**Comment by MaiteAlonso** [comment]
thank you for the answer

**Comment by renault-iaa** [comment]
We just publish a new version of dataset B where Fxxxxxxx planned trucks have been renamed into Pxxxxxxxx planned trucks.

**Comment by MaiteAlonso** [comment]
Sorry, but the new version of the B data has a bug in the VA and VA2 instances.
The parameter CJFM (distance between front and middle axle) is 0 in all trucks.

**Comment by renault-iaa** [comment]
Deeply sorry, there were additional separators which impact colums Cjfm and Ejhr in the files input trucks of instances VA and VA2. The corrected dataset B has been published.
