### ISSUE TITLE
Questions on final executable

### ISSUE THREAD

**Issue by ru-sec** [renault-iaa/challenge-roadef-2022#45]
Hello,
I have some questions about the final executable we need to deliver for the qualification phase:

1. What should the executable take in input? A string specifying the directory where the 3 files of an instance are located?

2. What should be the output of the executable? Should it save the output_files in the same folder where the input files are located or should it create a new folder with both input and output files? Any naming convention?

3. In the rules document it is specified that the executable should set the seed according to a parameter specified in input. From a practical point of view on the competition, I don't see why this is needed. Can't we "hard-code" the seed inside our solver? What are the drawbacks of doing so for this competition? Moreover, it is stated in the rules that the code will be run only once. So it is also not clear how can the organizers check if we use the seed specified in input or not and what would be the impact of not using it. Could you maybe explain a bit better why we need to have this input parameter?

4. Finally I was wondering if there is an environment where we can test that our executable can be correctly called by the VM in GCP or if we can send a preliminary version of the executable to just check with the organizers if the executable works or not. What happens if our program cannot run by the organizers because of some interface issue?

**Comment by renault-iaa** [comment]
Hello,

(1) and (2) We did not define the arguments of the executable in the rules, sorry. We expect the candidates to deliver a directory which contains a shell-script "run.sh" and all the files/sub-directories needed for the execution. The script will take 6 arguments :
1. pathname of file parameters
2. pathname of file input items
3. pathname of file input trucks
4. pathname of file output items
5. pathname of file output stacks
6. pathname of file output trucks

example of command line : run.sh ../datasetB/AS/input_parameters.csv  ../datasetB/AS/input_items.csv  ../datasetB/AS/input_trucks.csv  ../datasetB/AS/output_items.csv  ../datasetB/AS/output_stacks.csv  ../datasetB/AS/output_trucks.csv

We will run the script once for each instance, and interrupt the script once the timelimit parameterized for the instance is reached.

(3) The rule about the seed is just a warning. Proceed as you like, there is no constraint.

(4) We cannot provide you with GCP environments. But you can submit pre-releases of your executable from Mon 23 Jan until Fri 27 Jan, and re-submit a final release by 31 Jan. We will check wether the pre-release runs well on our GCP environment.
