### ISSUE TITLE
datasetC instance VO input files named inconsistently

### ISSUE THREAD

**Issue by hsimonis** [renault-iaa/challenge-roadef-2022#47]
Dear Organizers,

In the latest datasetC instance VO, two of the input files have a prefix VO_, which is unlike the naming schemes of previous datasets, where instances are already identified by the directory where they are stored in.  The files are
VO_input_items.csv
VO_input_trucks.csv

This is unnecessarily confusing, and should be changed. I don't know if any other instances in datasetC use this prefix naming method, most do not, it seems.

Regards

Helmut

**Comment by renault-iaa** [comment]
Sorry for the inconvenience. The instance VO has been corrected and dataset_C_3 (containing VO) has been republished.
