### ISSUE TITLE
DatasetC instance CA,CA2,CA3 truck length 1400

### ISSUE THREAD

**Issue by hsimonis** [renault-iaa/challenge-roadef-2022#48]
Dear Organizers,

In the instances CA,CA2,CA3 there are multiple lines that refer to trucks with a length of 1400. This seems quite short, compared to the length of 13500 or so of most other trucks. Is this intended, or a data error?

Example file input_truck.csv of instance CA
line 722, truck id P067402601, the next field after the truck id is length, value is 1400. Multiple other entries can be found by searching for ;1400;

If this is intended, then the other parameters for axle weight calculation do not seem to match  the given length of the truck.

Regards

Helmut

**Comment by renault-iaa** [comment]
Hello @hsimonis,

These trucks with length = 1400 are invalid. We will replace them. But before publishing a new version of dataset C, we have to make further checks.

Thanks for your patience

Best regards

**Comment by hsimonis** [comment]
Dear Organizers,
perhaps check the trucks of length 8620 in the AS,AS2,AS3 files, and trucks of length 7500 in TR,TR2,TR3 as well. The axle weight parameters of these trucks are the same as for the longer trucks, and the total weight in the TR cases as well, so these look suspicious as well.
The trucks with longer than usual length 17500 in the VAx files are slightly unusual as well, and do not have adjusted axle weight parameters compared to the 13500 long trucks. And finally, the ASx files have trucks of length 14940, slightly longer than the usual 13500 long trucks.

Best regards

Helmut

**Comment by renault-iaa** [comment]
Hello @hsimonis,

Trucks with length of 7500 and 14940 were already there in dataset B. You are right, the axle weights parameters are not adjusted for these trucks, nor for trucks with length of 8620 or 17500. However, you should be able to satisfy max axle weight constraints, even with not adjusted parameters. 

Best regards

**Comment by renault-iaa** [comment]
Hello @hsimonis,

Trucks with length of 1400 have been replaced by trucks with length of 13500 in instances CA, CA2 and CA3.

Best regards
