### ISSUE TITLE
Submission with Gurobi solver

### ISSUE THREAD

**Issue by WouterMe** [renault-iaa/challenge-roadef-2022#50]
Dear organizers,
 
We would like to use the Gurobi solver for our solution and we were wondering what we have to prepare for a correct submission. Currently, we have a floating license internally, which we are not allowed to send with out submission files. I understood from the Github post ([Gurobi license · Issue #41 · renault-iaa/challenge-roadef-2022 · GitHub](https://github.com/renault-iaa/challenge-roadef-2022/issues/41)) that you have your own Gurobi license. Does that mean that this Gurobi license is on the Google Cloud Platform on which you run the executables? Would it work if we add an input path for the Gurobi license folder in the run.sh file such that you can specify where the Gurobi license is located when running it from command line? Or is there something else we need to do?

Best regards,
Wouter

**Comment by renault-iaa** [comment]
Hello,

Yes we have a Gurobi licence on our GCP platform. So there is no problem to run your executable. And yes, you can add an input path for the Gurobi licence folder in the run.sh file. And that's enough.

Best regards
Alain Nguyen
