### ISSUE TITLE
Checker result.csv not well formed

### ISSUE THREAD

**Issue by hsimonis** [renault-iaa/challenge-roadef-2022#51]
Hi all,
I don't know if this counts as a bug or a feature for the checker. When running the checker on one of my result files (instance DO in dataset C), the resulting report.csv contains a line  

java.lang.IllegalArgumentException: the supplier (stack empty) of stack Q102215001_2_3 has no loading order !!

which does not conform to the csv structure, and is therefore creating a problem when I try to read the file. On the other hand, it seems that the checker did not crash, the result file contains more messages after this line.

Full solution files and results available on request.

Best regards

Helmut

**Comment by renault-iaa** [comment]
Hello Helmut,

It seems that you build the stack Q102215001_2_3 without any item associated, hence the strange supplier code "stack empty". Can you send us the solution files so that we can analyse thoroughly the issue ? 

Thanks
Alain
