### ISSUE TITLE
Typos on page 4 and 8 (?)

### ISSUE THREAD

**Issue by MartinJGeiger** [renault-iaa/challenge-roadef-2022#7]
I think that there are some typos in the formulas on page 4, second bullet point, where there is $x^e_s$ (but it should be $sx^e_s$, etc.), and then in the third bullet point, with $z^e_s$ instead of (what I believe to be correct) $sz^e_s$.

Probably, on page 8, when explaining condition (3) in line 10, $GE_{g_{s_{1}}} \leq GE_{g_{s_{2}}}$ should not read $\leq$ but simply $<$.

**Comment by renault-iaa** [comment]
You are right. Corrections will be made on the next version v1.2 of the subject.
