### ISSUE TITLE
Computation of $ej^{e}$

### ISSUE THREAD

**Issue by MartinJGeiger** [renault-iaa/challenge-roadef-2022#8]
Dear organizers,
I know that we have been in touch about this before, but I still have a hard time with the formula for  $ej^e$. If I understand the coordinates correctly, then the origin is next to the driver cabin, so the formula should express the distance of the center of gravity to the driver cabin.
So how can this match the definition given in Figure 11?

To illustrate, let us consider a truck with a single stack. Obviously, this stack $s$ must be placed next to the driver cabin ("leftmost"), so $sx^o_s = 0$. Therefore, $ej^e$ will assume a small numerical value (in case the size of this stack is considerable smaller than the length of the trailer, which probably holds for most stacks). It follows that the distance to the "end" is expressed by a larger numerical value, but this does not match the formula.

**Comment by renault-iaa** [comment]
Again you are right. Due to a misunderstanding with my colleagues, I define ej^e as the distance between the end of the trailer and the center of gravity, while in fact it represents the distance between the driver's cabin and the center of gravity. The subject will be updated (=> v1.3).

**Comment by MartinJGeiger** [comment]
thank you
