### ISSUE TITLE
Inconsistency between item dock and truck dock

### ISSUE THREAD

**Issue by Coloquinte** [renault-iaa/challenge-roadef-2022#9]
Hi,

In some instances, there is no truck matching the dock assigned to an item. For example, in BY, item 0090016900_03072022000936 has product code 808640012R and plant dock GRD7, but the only trucks with product code 808640012R use plant dock GRD9. How should we resolve these apparent inconsistencies?

Thanks,
Gabriel

**Comment by renault-iaa** [comment]
Hello Gabriel,

You are absolutely right. There are issues with our program generating datasets. This product code is associated with 2 plant docks, GRD7 and GRD9, but we miss the first plant dock when we generate the trucks file. We have to re-generate the dataset A.

Best regards
Alain Nguyen

**Comment by Coloquinte** [comment]
Thanks Alain!

**Comment by renault-iaa** [comment]
We have published a new version of dataset A. The issue about plant dock in items vs plant docks in planned trucks has been solved.
